name: PR Test Build linux

on: [push]


jobs:
  step_one:
    runs-on: ubuntu-20.04
    env:
      STORE_PASS: test@cake_wallet
      KEY_PASS: test@cake_wallet
      PR_NUMBER: 1234

    steps:
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - name: is pr
        if: github.event_name == 'pull_request'
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF}" >> $GITHUB_ENV

      - name: is not pr
        if: github.event_name != 'pull_request'
        run: echo "BRANCH_NAME=${{ github.event.inputs.branch }}" >> $GITHUB_ENV

      - name: temp
        run: echo "BRANCH_NAME=main" >> $GITHUB_ENV


      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"
      - name: Configure placeholder git details
        run: |
          git config --global user.email "CI@cakewallet.com"
          git config --global user.name "Cake Github Actions"
      - name: Flutter action
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.19.6"
          channel: stable

      - name: Install package dependencies
        run: |
          sudo apt update
          sudo apt-get install -y curl unzip automake build-essential file pkg-config git python-is-python3 libtool libtinfo5 cmake clang

      - name: Install desktop dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build libgtk-3-dev gperf
          sudo apt install -y build-essential pkg-config autoconf libtool ccache make cmake gcc g++ git curl lbzip2 libtinfo5 gperf gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64
      - name: Execute Build and Setup Commands
        run: |
          sudo mkdir -p /opt/android
          sudo chown $USER /opt/android
          cd /opt/android
          -y curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          cargo install cargo-ndk
          git clone https://github.com/cake-tech/cake_wallet.git --branch ${{ env.BRANCH_NAME }}
          cd scripts && ./gen_android_manifest.sh && cd ..
          cd cake_wallet/scripts/android/
          source ./app_env.sh cakewallet
          ./app_config.sh
          cd ../../..
          cd cake_wallet/scripts/windows/
          source ./app_env.sh cakewallet
          ./app_config.sh
          cd ../../..

      - name: Cache Externals
        id: cache-externals
        uses: actions/cache@v3
        with:
          path: |
            /opt/android/cake_wallet/cw_haven/android/.cxx
            /opt/android/cake_wallet/scripts/monero_c/release
          key: windows-${{ hashFiles('**/prepare_moneroc.sh' ,'**/build_monero_all.sh') }}

      - if: ${{ steps.cache-externals.outputs.cache-hit != 'true' }}
        name: Generate Externals
        run: |
          cd /opt/android/cake_wallet/scripts/windows/
          source ./app_env.sh cakewallet
          ./build_monero_all.sh

      - name: Install Flutter dependencies
        run: |
          cd /opt/android/cake_wallet
          flutter pub get

      - name: Generate localization
        run: |
          cd /opt/android/cake_wallet
          flutter packages pub run tool/generate_localization.dart

      - name: Build generated code
        run: |
          cd /opt/android/cake_wallet
          ./model_generator.sh

      - name: Add secrets
        run: |
          cd /opt/android/cake_wallet
          touch lib/.secrets.g.dart
          touch cw_evm/lib/.secrets.g.dart
          touch cw_solana/lib/.secrets.g.dart
          touch cw_core/lib/.secrets.g.dart
          touch cw_nano/lib/.secrets.g.dart
          touch cw_tron/lib/.secrets.g.dart
          echo "const salt = '0ef79b08c4904cd56d4caad1d165de1d';" > lib/.secrets.g.dart
          echo "const keychainSalt = 'f393a453df428062ca119b87';" >> lib/.secrets.g.dart
          echo "const key = 'accf301f3a9a371ca29cea2c0e70dd39';" >> lib/.secrets.g.dart
          echo "const walletSalt = '9ae985b8';" >> lib/.secrets.g.dart
          echo "const shortKey = '8b9343a3f82ad2d8bab27157';" >> lib/.secrets.g.dart
          echo "const backupSalt = '3eef42870206cb21';" >> lib/.secrets.g.dart
          echo "const backupKeychainSalt = 'ee58dceadca7e88a1c9d8e15';" >> lib/.secrets.g.dart
          echo "const changeNowApiKey = '';" >> lib/.secrets.g.dart
          echo "const changeNowApiKeyDesktop = '';" >> lib/.secrets.g.dart
          echo "const wyreSecretKey = '';" >> lib/.secrets.g.dart
          echo "const wyreApiKey = '';" >> lib/.secrets.g.dart
          echo "const wyreAccountId = '';" >> lib/.secrets.g.dart
          echo "const moonPayApiKey = '';" >> lib/.secrets.g.dart
          echo "const moonPaySecretKey = '';" >> lib/.secrets.g.dart
          echo "const sideShiftAffiliateId = '';" >> lib/.secrets.g.dart
          echo "const simpleSwapApiKey = '';" >> lib/.secrets.g.dart
          echo "const simpleSwapApiKeyDesktop = '';" >> lib/.secrets.g.dart
          echo "const onramperApiKey = '';" >> lib/.secrets.g.dart
          echo "const anypayToken = '';" >> lib/.secrets.g.dart
          echo "const ioniaClientId = '';" >> lib/.secrets.g.dart
          echo "const twitterBearerToken = '';" >> lib/.secrets.g.dart
          echo "const trocadorApiKey = '';" >> lib/.secrets.g.dart
          echo "const trocadorExchangeMarkup = '';" >> lib/.secrets.g.dart
          echo "const anonPayReferralCode = '';" >> lib/.secrets.g.dart
          echo "const fiatApiKey = '';" >> lib/.secrets.g.dart
          echo "const payfuraApiKey = '';" >> lib/.secrets.g.dart
          echo "const ankrApiKey = '';" >> lib/.secrets.g.dart
          echo "const etherScanApiKey = '';" >> cw_evm/lib/.secrets.g.dart
          echo "const moralisApiKey = '';" >> cw_evm/lib/.secrets.g.dart
          echo "const chatwootWebsiteToken = '';" >> lib/.secrets.g.dart
          echo "const exolixApiKey = '';" >> lib/.secrets.g.dart
          echo "const robinhoodApplicationId = '';" >> lib/.secrets.g.dart
          echo "const exchangeHelperApiKey = '';" >> lib/.secrets.g.dart
          echo "const walletConnectProjectId = '';" >> lib/.secrets.g.dart
          echo "const moralisApiKey = '';" >> lib/.secrets.g.dart
          echo "const polygonScanApiKey = '';" >> cw_evm/lib/.secrets.g.dart
          echo "const ankrApiKey = '';" >> cw_solana/lib/.secrets.g.dart
          echo "const testCakePayApiKey = '';" >> lib/.secrets.g.dart
          echo "const cakePayApiKey = '';" >> lib/.secrets.g.dart
          echo "const authorization = '';" >> lib/.secrets.g.dart
          echo "const CSRFToken = '';" >> lib/.secrets.g.dart
          echo "const quantexExchangeMarkup = '';" >> lib/.secrets.g.dart
          echo "const nano2ApiKey = '';" >> cw_nano/lib/.secrets.g.dart
          echo "const nanoNowNodesApiKey = '';" >> cw_nano/lib/.secrets.g.dart
          echo "const tronGridApiKey = '';" >> cw_tron/lib/.secrets.g.dart
          echo "const tronNowNodesApiKey = '';" >> cw_tron/lib/.secrets.g.dart
  step_two:
    needs: step_one
    runs-on: ubuntu-20.04
    env:
      STORE_PASS: test@cake_wallet
      KEY_PASS: test@cake_wallet
      PR_NUMBER: 1234
    steps:

      - name: temp
        run: echo "BRANCH_NAME=main" >> $GITHUB_ENV
      - name: Flutter action
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.19.6"
          channel: stable
      - name: Build
        run: |
          cd /opt/android/cake_wallet
          flutter build windows --release

      - name: Prepare release zip file
        run: |
          cakewallet.bat

      - name: Upload Artifact
        uses: kittaakos/upload-artifact-as-is@v0
        with:
          path: /opt/android/cake_wallet/build/linux/x64/release/${{env.BRANCH_NAME}}.zip

      - name: Send Test APK
        continue-on-error: true
        uses: adrey/slack-file-upload-action@1.0.5
        with:
          token: ${{ secrets.SLACK_APP_TOKEN }}
          path: /opt/android/cake_wallet/build/linux/x64/release/${{env.BRANCH_NAME}}.zip
          channel: ${{ secrets.SLACK_APK_CHANNEL }}
          title: "${{ env.BRANCH_NAME }}_linux.zip"
          filename: ${{ env.BRANCH_NAME }}_linux.zip
          initial_comment: ${{ github.event.head_commit.message }}
